# Generated by Django 4.1.2 on 2023-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
